import { useState } from "react";
import { useLocation } from "wouter";
import { trpc } from "@/lib/trpc";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Card, CardContent } from "@/components/ui/card";
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle } from "@/components/ui/alert-dialog";
import { ArchiveRestore, Download, Edit3, Eye, Plus, Search, Trash2, UserRound, UserX } from "lucide-react";
import { toast } from "sonner";
import { EmptyState, LoadingState, PageHeader } from "@/components/AppCommon";
import { CustomerDialog } from "@/components/CustomerDialog";
import { downloadCsv } from "@/lib/export";
import { formatRs } from "@shared/billing";

export default function Customers() {
  const [, navigate] = useLocation();
  const [search, setSearch] = useState("");
  const [view, setView] = useState<"active" | "closed">("active");
  const [open, setOpen] = useState(false);
  const [editing, setEditing] = useState<any>();
  const [deleting, setDeleting] = useState<any>();
  const [closing, setClosing] = useState<any>();
  const [closeReason, setCloseReason] = useState("Customer no longer uses the service.");
  const query = trpc.customers.list.useQuery({ search, status: view });
  const access = trpc.admin.myAccess.useQuery();
  const utils = trpc.useUtils();
  const close = trpc.customers.close.useMutation({ onSuccess: result => { toast.success(`Customer closed. Final reading saved: ${result.finalReading ?? 0}.`); setClosing(undefined); void utils.customers.invalidate(); void utils.overview.invalidate(); void utils.bills.invalidate(); }, onError: e => toast.error(e.message) });
  const reactivate = trpc.customers.reactivate.useMutation({ onSuccess: () => { toast.success("Customer re-activated and returned to Active Customers."); void utils.customers.invalidate(); void utils.overview.invalidate(); void utils.bills.invalidate(); }, onError: e => toast.error(e.message) });
  const del = trpc.customers.delete.useMutation({ onSuccess: () => { toast.success("Customer deleted"); setDeleting(undefined); void utils.customers.invalidate(); }, onError: e => toast.error(e.message) });
  if (query.isLoading) return <LoadingState label="Loading customers…" />;
  const rows = query.data || [];
  const title = view === "active" ? "Active Customers" : "Closed Customers";
  return <>
    <PageHeader eyebrow="Customer management" title={title} description={view === "active" ? "Manage customers currently using your service." : "Closed customer IDs remain here with all billing history preserved."} actions={<div className="flex flex-wrap gap-2"><Button variant={view === "active" ? "default" : "outline"} onClick={() => setView("active")}>Active Customers</Button><Button variant={view === "closed" ? "default" : "outline"} onClick={() => setView("closed")}><ArchiveRestore className="mr-2 h-4 w-4" />Closed Customers</Button>{rows.length > 0 && <Button variant="outline" onClick={() => downloadCsv(`${view}-customers.csv`, rows.map((c: any) => ({ Serial: c.serialNumber, Name: c.name, Status: c.lifecycleStatus, Mobile: c.mobileNumber, WhatsApp: c.whatsappNumber, CNIC: c.cnic, Address: c.address, Meter: c.meterNumber, Area: c.meterLocation, UnitPrice: c.unitPrice, Outstanding: c.outstanding || 0, ClosedAt: c.closedAt || "" })))}><Download className="mr-2 h-4 w-4" />CSV</Button>}{view === "active" && access.data?.canManageCustomers && <Button onClick={() => { setEditing(undefined); setOpen(true); }}><Plus className="mr-2 h-4 w-4" />Add Customer</Button>}</div>} />
    <div className="relative mb-5 max-w-lg"><Search className="absolute left-3 top-3.5 h-4 w-4 text-muted-foreground" /><Input value={search} onChange={e => setSearch(e.target.value)} placeholder="Search name, mobile, or meter number…" className="h-11 bg-card pl-9" /></div>
    {!rows.length ? <EmptyState title={`No ${view} customers found`} description={view === "active" ? "Add your first customer to start monthly billing." : "Closed customers will appear here without losing their history."} actionLabel={view === "active" && access.data?.canManageCustomers ? "Add Customer" : undefined} onAction={() => setOpen(true)} /> : <div className="grid gap-3 lg:grid-cols-2 2xl:grid-cols-3">{rows.map((c: any) => <Card key={c.id} className="glass-card"><CardContent className="p-4"><div className="flex gap-4"><div className="h-16 w-16 shrink-0 overflow-hidden rounded-2xl bg-[#1a2b4a] text-[#d9ad51]">{c.photoUrl ? <img src={c.photoUrl} className="h-full w-full object-cover" /> : <div className="flex h-full items-center justify-center"><UserRound /></div>}</div><div className="min-w-0 flex-1"><div className="flex items-start justify-between gap-2"><div><p className="text-xs font-bold uppercase tracking-wider text-[#a7761f]">Customer #{String(c.sNo ?? c.serialNumber).padStart(3, "0")}</p><h3 className="truncate text-xl">{c.name}</h3><span className={`mt-1 inline-flex rounded-full px-2 py-0.5 text-[10px] font-bold uppercase ${view === "closed" ? "bg-slate-200 text-slate-700" : "bg-emerald-100 text-emerald-700"}`}>{view === "closed" ? "Closed / Inactive" : "Active"}</span></div><p className="text-right text-xs text-muted-foreground">Outstanding<br /><strong className={(c.outstanding || 0) > 0 ? "text-destructive" : "text-emerald-700"}>{formatRs(c.outstanding || 0)}</strong></p></div><p className="mt-2 truncate text-xs text-muted-foreground">{c.mobileNumber || "No mobile"} · {c.meterNumber || "No meter"}</p><p className="truncate text-xs text-muted-foreground">{c.meterLocation || c.address || "Location not set"}</p>{view === "closed" && <p className="mt-2 text-xs text-slate-600">{c.closeReason || "Customer no longer uses the service."}{c.closedAt ? ` · ${new Date(c.closedAt).toLocaleDateString()}` : ""}</p>}</div></div><div className="mt-4 grid grid-cols-2 gap-2 sm:grid-cols-4"><Button variant="outline" className="min-h-11" onClick={() => navigate(`/customer/${c.id}`)}><Eye className="mr-1 h-4 w-4" />View</Button>{access.data?.canManageCustomers && <><Button variant="outline" className="min-h-11" onClick={() => { setEditing(c); setOpen(true); }}><Edit3 className="mr-1 h-4 w-4" />Edit</Button>{view === "active" ? <Button variant="outline" className="min-h-11 text-amber-700" onClick={() => { setClosing(c); setCloseReason("Customer no longer uses the service."); }}><UserX className="mr-1 h-4 w-4" />Close ID</Button> : <Button variant="outline" className="min-h-11 text-emerald-700" onClick={() => reactivate.mutate({ id: c.id })} disabled={reactivate.isPending}><ArchiveRestore className="mr-1 h-4 w-4" />Re-activate</Button>}<Button variant="outline" className="min-h-11 text-destructive" onClick={() => setDeleting(c)}><Trash2 className="h-4 w-4" /></Button></>}</div></CardContent></Card>)}</div>}
    <CustomerDialog open={open} onOpenChange={setOpen} customer={editing} />
    <AlertDialog open={Boolean(closing)} onOpenChange={v => !v && setClosing(undefined)}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Close {closing?.name} customer ID?</AlertDialogTitle><AlertDialogDescription>This keeps the final meter reading, all bills, payments, and history. The customer will be removed from Active Customers and dashboard current data, but remain available under Closed Customers.</AlertDialogDescription></AlertDialogHeader><Textarea value={closeReason} onChange={e => setCloseReason(e.target.value)} placeholder="Reason for closing" /><AlertDialogFooter><AlertDialogCancel>Cancel</AlertDialogCancel><AlertDialogAction onClick={() => closing && close.mutate({ id: closing.id, reason: closeReason })} disabled={close.isPending}>Close Customer ID</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
    <AlertDialog open={Boolean(deleting)} onOpenChange={v => !v && setDeleting(undefined)}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Delete {deleting?.name}?</AlertDialogTitle><AlertDialogDescription>Permanent deletion is still allowed only when the customer has no bills. Use Close ID instead to preserve existing records.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>Cancel</AlertDialogCancel><AlertDialogAction className="bg-destructive" onClick={() => deleting && del.mutate({ id: deleting.id })}>Delete Customer</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
  </>;
}
