import { TRPCError } from "@trpc/server";
import { and, asc, desc, eq, gte, lte, lt, or } from "drizzle-orm";
import { z } from "zod";
import { customerDailyWapdaRecords, customers, monthlyBills } from "../../drizzle/schema";
import { DEFAULT_ELECTRICITY_RATE, getCurrentCharges, getOutstanding, getTotalPayable, getUnits, getBillStatus, invoiceNumber } from "../../shared/billing";
import { protectedProcedure, router } from "../_core/trpc";
import { requireAccess } from "../access";
import { getDb } from "../db";

const periodInput = z.object({ month: z.number().int().min(1).max(12), year: z.number().int().min(2000).max(9999) });
const rangeInput = z.object({ startDate: z.string().regex(/^\d{4}-\d{2}-\d{2}$/), endDate: z.string().regex(/^\d{4}-\d{2}-\d{2}$/), month: z.number().int().min(1).max(12), year: z.number().int().min(2000).max(9999) });
const importInput = z.object({ data: z.unknown(), readingDate: z.string().regex(/^\d{4}-\d{2}-\d{2}$/).optional(), month: z.number().int().min(1).max(12).optional(), year: z.number().int().min(2000).max(9999).optional() });
const rowInput = z.object({ id: z.number().int().positive(), previousReading: z.number().nonnegative(), currentReading: z.number().nonnegative(), ratePerUnit: z.number().nonnegative().optional() });
const manualInput = z.object({ customerId: z.number().int().positive(), month: z.number().int().min(1).max(12), year: z.number().int().min(2000).max(9999), readingDate: z.string().regex(/^\d{4}-\d{2}-\d{2}$/), previousReading: z.number().nonnegative().optional(), currentReading: z.number().nonnegative(), ratePerUnit: z.number().nonnegative().optional() });

export type DailyCustomerEntry = { index: number; sNo?: number; nameTag?: string; previousReading?: number; currentReading: number; unitsConsumed?: number; ratePerUnit?: number };
function parseJson(value: unknown): unknown { let current = value; for (let i = 0; i < 3 && typeof current === "string"; i++) { try { current = JSON.parse(current.trim()); } catch { break; } } return current; }
function toFinite(value: unknown, fallback?: number) { if (value === undefined || value === null || value === "") return fallback; const number = Number(value); return Number.isFinite(number) ? number : undefined; }
function normalizeName(value: string) { return value.normalize("NFKC").toLocaleLowerCase().replace(/[._'’\-]+/g, " ").replace(/[^a-z0-9\s]+/g, " ").replace(/\s+/g, " ").trim(); }
function parsePeriod(root: Record<string, unknown>, input: { readingDate?: string; month?: number; year?: number }) { const date = input.readingDate ?? (typeof root.date === "string" ? root.date : undefined); let month = input.month; let year = input.year; if (date) { const match = date.match(/^(\d{4})-(\d{2})-(\d{2})$/); if (!match) throw new TRPCError({ code: "BAD_REQUEST", message: "date must be YYYY-MM-DD." }); year ??= Number(match[1]); month ??= Number(match[2]); const parsed = new Date(`${date}T00:00:00Z`); if (Number.isNaN(parsed.getTime()) || parsed.getUTCFullYear() !== year || parsed.getUTCMonth() + 1 !== month) throw new TRPCError({ code: "BAD_REQUEST", message: "The selected date does not belong to the selected month and year." }); } if (!month || !year) { const period = typeof root.billingPeriod === "string" ? root.billingPeriod.match(/(January|February|March|April|May|June|July|August|September|October|November|December)\s+(\d{4})/i) : null; const names = ["january", "february", "march", "april", "may", "june", "july", "august", "september", "october", "november", "december"]; if (period) { month ??= names.indexOf(period[1].toLowerCase()) + 1; year ??= Number(period[2]); } } if (!month || !year) throw new TRPCError({ code: "BAD_REQUEST", message: "Select a month and year, or include billingPeriod/date in the JSON." }); return { month, year, readingDate: date ?? `${year}-${String(month).padStart(2, "0")}-01` }; }
export function normalizeCustomerDailyPayload(raw: unknown): { root: Record<string, unknown>; entries: DailyCustomerEntry[]; invalid: Array<{ index: number; name?: string; reason: string }> } { const parsed = parseJson(raw); const root = !Array.isArray(parsed) && parsed && typeof parsed === "object" ? parsed as Record<string, unknown> : {}; const source = Array.isArray(parsed) ? parsed : parseJson(root.customers); if (!Array.isArray(source)) throw new TRPCError({ code: "BAD_REQUEST", message: "JSON must contain a customers array." }); const entries: DailyCustomerEntry[] = []; const invalid: Array<{ index: number; name?: string; reason: string }> = []; for (let index = 0; index < source.length; index++) { const row = parseJson(source[index]); if (!row || typeof row !== "object") { invalid.push({ index, reason: "Each customer entry must be an object." }); continue; } const value = row as Record<string, unknown>; const customerId = typeof value.customerId === "string" ? value.customerId.match(/(\d+)$/) : null; const sNoValue = value.sNo ?? value.serialNumber ?? (customerId ? Number(customerId[1]) : undefined); const sNo = toFinite(sNoValue); const nameTag = String(value.nameTag ?? value.name ?? "").trim() || undefined; const currentReading = toFinite(value.currentReading ?? value.current ?? value.reading); const previousReading = toFinite(value.previousReading ?? value.previous); const unitsConsumed = toFinite(value.unitsConsumed ?? value.units ?? value.consumption); const ratePerUnit = toFinite(value.ratePerUnit ?? root.defaultRatePerUnit, DEFAULT_ELECTRICITY_RATE); if (!sNo && !nameTag) { invalid.push({ index, reason: "sNo or name is required." }); continue; } if (currentReading === undefined || currentReading < 0) { invalid.push({ index, name: nameTag, reason: "currentReading must be a finite non-negative number." }); continue; } if (previousReading !== undefined && previousReading < 0) { invalid.push({ index, name: nameTag, reason: "previousReading cannot be negative." }); continue; } if (ratePerUnit === undefined || ratePerUnit < 0) { invalid.push({ index, name: nameTag, reason: "ratePerUnit must be a finite non-negative number." }); continue; } const calculatedUnits = previousReading === undefined ? currentReading : getUnits(previousReading, currentReading); if (!Number.isFinite(calculatedUnits) || calculatedUnits < 0) { invalid.push({ index, name: nameTag, reason: "unitsConsumed cannot be negative." }); continue; } entries.push({ index, sNo: sNo && Number.isInteger(sNo) ? sNo : undefined, nameTag, previousReading, currentReading, unitsConsumed: calculatedUnits, ratePerUnit }); } return { root, entries, invalid }; }

async function syncMonthlyBill(db: any, customerId: number, month: number, year: number) {
  const [customer] = await db.select().from(customers).where(eq(customers.id, customerId)).limit(1); if (!customer) return null;
  const rows: any[] = await db.select().from(customerDailyWapdaRecords).where(and(eq(customerDailyWapdaRecords.customerId, customerId), eq(customerDailyWapdaRecords.month, month), eq(customerDailyWapdaRecords.year, year))).orderBy(asc(customerDailyWapdaRecords.readingDate));
  const [existing] = await db.select().from(monthlyBills).where(and(eq(monthlyBills.customerId, customerId), eq(monthlyBills.month, month), eq(monthlyBills.year, year))).limit(1);
  if (!rows.length) return existing ?? null;
  const calculated = calculateMonthlyDailyBill(rows, Number(customer.unitPrice || DEFAULT_ELECTRICITY_RATE), existing?.previousOutstanding ?? 0, existing?.discount ?? 0, existing?.lateFee ?? 0, Math.min(existing?.receivedAmount ?? 0, Number.MAX_SAFE_INTEGER), existing?.dueDate ?? `${year}-${String(month).padStart(2, "0")}-${String(new Date(year, month, 0).getDate()).padStart(2, "0")}`);
  const { previousReading, currentReading, unitsConsumed, unitPrice, amount, previousOutstanding, discount, lateFee, totalPayable, receivedAmount, outstandingAmount, status, dueDate } = calculated; const values = { customerName: customer.name, previousReading, currentReading, unitsConsumed, unitPrice, amount, totalPayable, receivedAmount, outstandingAmount, status, readingDate: rows[rows.length - 1].readingDate, issuedDate: existing?.issuedDate ?? `${year}-${String(month).padStart(2, "0")}-01`, dueDate };
  if (existing) await db.update(monthlyBills).set(values).where(eq(monthlyBills.id, existing.id)); else await db.insert(monthlyBills).values({ customerId, customerName: customer.name, invoiceNumber: invoiceNumber(year, month, customer.serialNumber), month, year, previousReading, currentReading, unitsConsumed, unitPrice, previousOutstanding, amount, discount, lateFee, totalPayable, receivedAmount, outstandingAmount: getOutstanding(totalPayable, receivedAmount), readingDate: rows[rows.length - 1].readingDate, meterReaderName: null, meterReadingPhotoUrl: null, issuedDate: values.issuedDate, dueDate, receivedDate: null, paymentMethod: null, remarks: "Created from customer daily WAPDA records", status: values.status });
  return values;
}

export function calculateMonthlyDailyBill(rows: Array<{ previousReading: number; currentReading: number; unitsConsumed: number; readingDate: string }>, unitPrice: number, previousOutstanding = 0, discount = 0, lateFee = 0, receivedAmount = 0, dueDate = "2099-12-31") {
  const previousReading = rows[0]?.previousReading ?? 0; const currentReading = rows[rows.length - 1]?.currentReading ?? previousReading; const unitsConsumed = rows.reduce((sum, row) => sum + Number(row.unitsConsumed), 0); const amount = getCurrentCharges(unitsConsumed, unitPrice); const totalPayable = getTotalPayable(previousOutstanding, amount, lateFee, discount); const received = Math.min(receivedAmount, totalPayable); return { previousReading, currentReading, unitsConsumed, unitPrice, amount, previousOutstanding, discount, lateFee, totalPayable, receivedAmount: received, outstandingAmount: getOutstanding(totalPayable, received), status: getBillStatus(totalPayable, received, dueDate), dueDate };
}

export function calculateManualCustomerReading(previousReading: number, currentReading: number, ratePerUnit: number) {
  if (currentReading < previousReading) throw new Error("Current reading cannot be lower than previous reading.");
  const unitsConsumed = getUnits(previousReading, currentReading);
  return { unitsConsumed, totalAmount: Math.round(unitsConsumed * ratePerUnit) };
}

export function summarizeCustomerRange(rows: Array<{ customerId: number; customerName: string | null; sNo: number; readingDate: string; unitsConsumed: number; totalAmount: number }>) {
  const byCustomer = new Map<number, { customerId: number; customerName: string | null; sNo: number; days: number; units: number; totalAmount: number }>();
  for (const row of rows) { const current = byCustomer.get(row.customerId) ?? { customerId: row.customerId, customerName: row.customerName, sNo: row.sNo, days: 0, units: 0, totalAmount: 0 }; current.days += 1; current.units += Number(row.unitsConsumed); current.totalAmount += Number(row.totalAmount); byCustomer.set(row.customerId, current); }
  return { totalRecords: rows.length, importedDays: new Set(rows.map(row => row.readingDate)).size, totalUnits: rows.reduce((sum, row) => sum + Number(row.unitsConsumed), 0), totalAmount: rows.reduce((sum, row) => sum + Number(row.totalAmount), 0), customers: Array.from(byCustomer.values()).sort((a, b) => a.sNo - b.sNo) };
}

async function loadPreview(db: any, raw: unknown, readingDate?: string, month?: number, year?: number) { const normalized = normalizeCustomerDailyPayload(raw); const period = parsePeriod(normalized.root, { readingDate, month, year }); const allCustomers: any[] = await db.select().from(customers).orderBy(asc(customers.sNo)); const periodRows: any[] = await db.select().from(customerDailyWapdaRecords).where(and(eq(customerDailyWapdaRecords.month, period.month), eq(customerDailyWapdaRecords.year, period.year))).orderBy(asc(customerDailyWapdaRecords.sNo), asc(customerDailyWapdaRecords.readingDate)); const bySNo = new Map(allCustomers.map(row => [row.sNo, row])); const byName = new Map(allCustomers.map(row => [normalizeName(row.name), row])); const existing = new Map(periodRows.map(row => [`${row.customerId}:${row.readingDate}`, row])); const prior = new Map<number, any>(); for (const row of periodRows) if (row.readingDate < period.readingDate) prior.set(row.customerId, row); const seen = new Set<number>(); const matched: any[] = []; const notFound: any[] = []; const duplicates: any[] = []; for (const entry of normalized.entries) { const customer = entry.sNo ? bySNo.get(entry.sNo) : (entry.nameTag ? byName.get(normalizeName(entry.nameTag)) : undefined); if (!customer) { notFound.push({ index: entry.index, sNo: entry.sNo, name: entry.nameTag, reading: entry.currentReading, reason: "Existing customer was not found. No customer was created." }); continue; } if (seen.has(customer.id)) { duplicates.push({ index: entry.index, sNo: entry.sNo, name: entry.nameTag, reason: "Duplicate customer in this upload." }); continue; } seen.add(customer.id); const previousReading = entry.previousReading ?? prior.get(customer.id)?.currentReading ?? 0; const unitsConsumed = getUnits(previousReading, entry.currentReading); const ratePerUnit = entry.ratePerUnit ?? DEFAULT_ELECTRICITY_RATE; const old = existing.get(`${customer.id}:${period.readingDate}`); matched.push({ index: entry.index, customerId: customer.id, sNo: customer.sNo, customerName: customer.name, readingDate: period.readingDate, previousReading, currentReading: entry.currentReading, unitsConsumed, ratePerUnit, totalAmount: Math.round(unitsConsumed * ratePerUnit), existingId: old?.id ?? null, action: old ? "update" : "create" }); } return { ...period, totalRecords: normalized.entries.length + normalized.invalid.length, matched, notFound, invalid: normalized.invalid, duplicates, updated: matched.filter(row => row.action === "update").length, created: matched.filter(row => row.action === "create").length }; }

export const customerDailyWapdaRouter = router({
  customer: protectedProcedure.input(z.object({ customerId: z.number().int().positive(), month: z.number().int().min(1).max(12), year: z.number().int().min(2000).max(9999) })).query(async ({ ctx, input }) => { await requireAccess(ctx.user, "canViewCustomers"); const db = await getDb(); if (!db) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR", message: "Database unavailable" }); return db.select().from(customerDailyWapdaRecords).where(and(eq(customerDailyWapdaRecords.customerId, input.customerId), eq(customerDailyWapdaRecords.month, input.month), eq(customerDailyWapdaRecords.year, input.year))).orderBy(asc(customerDailyWapdaRecords.readingDate)); }),
  customerYear: protectedProcedure.input(z.object({ customerId: z.number().int().positive(), year: z.number().int().min(2000).max(9999) })).query(async ({ ctx, input }) => { await requireAccess(ctx.user, "canViewCustomers"); const db = await getDb(); if (!db) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR", message: "Database unavailable" }); return db.select().from(customerDailyWapdaRecords).where(and(eq(customerDailyWapdaRecords.customerId, input.customerId), eq(customerDailyWapdaRecords.year, input.year))).orderBy(asc(customerDailyWapdaRecords.month), asc(customerDailyWapdaRecords.readingDate)); }),
  list: protectedProcedure.input(periodInput).query(async ({ ctx, input }) => { await requireAccess(ctx.user, "canViewReports"); const db = await getDb(); if (!db) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR", message: "Database unavailable" }); return db.select().from(customerDailyWapdaRecords).where(and(eq(customerDailyWapdaRecords.month, input.month), eq(customerDailyWapdaRecords.year, input.year))).orderBy(asc(customerDailyWapdaRecords.sNo), asc(customerDailyWapdaRecords.readingDate)); }),
  preview: protectedProcedure.input(importInput).mutation(async ({ ctx, input }) => { await requireAccess(ctx.user, "canManageWapda"); const db = await getDb(); if (!db) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR", message: "Database unavailable" }); return loadPreview(db, input.data, input.readingDate, input.month, input.year); }),
  confirm: protectedProcedure.input(importInput).mutation(async ({ ctx, input }) => { await requireAccess(ctx.user, "canManageWapda"); const db = await getDb(); if (!db) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR", message: "Database unavailable" }); return db.transaction(async (tx: any) => { const preview = await loadPreview(tx, input.data, input.readingDate, input.month, input.year); for (const row of preview.matched) { await tx.insert(customerDailyWapdaRecords).values({ customerId: row.customerId, customerName: row.customerName, sNo: row.sNo, month: preview.month, year: preview.year, readingDate: row.readingDate, previousReading: row.previousReading, currentReading: row.currentReading, unitsConsumed: row.unitsConsumed, ratePerUnit: row.ratePerUnit, totalAmount: row.totalAmount }).onDuplicateKeyUpdate({ set: { customerName: row.customerName, sNo: row.sNo, previousReading: row.previousReading, currentReading: row.currentReading, unitsConsumed: row.unitsConsumed, ratePerUnit: row.ratePerUnit, totalAmount: row.totalAmount } }); await syncMonthlyBill(tx, row.customerId, preview.month, preview.year); } return { success: true, ...preview, imported: preview.matched.length }; }); }),
  manualSave: protectedProcedure.input(manualInput).mutation(async ({ ctx, input }) => { await requireAccess(ctx.user, "canManageWapda"); const parsedDate = new Date(`${input.readingDate}T00:00:00Z`); if (Number.isNaN(parsedDate.getTime()) || parsedDate.getUTCFullYear() !== input.year || parsedDate.getUTCMonth() + 1 !== input.month) throw new TRPCError({ code: "BAD_REQUEST", message: "Reading date must belong to the selected month and year." }); const db = await getDb(); if (!db) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR", message: "Database unavailable" }); const [customer] = await db.select().from(customers).where(eq(customers.id, input.customerId)).limit(1); if (!customer) throw new TRPCError({ code: "NOT_FOUND", message: "Customer not found." }); const [previousRow] = await db.select().from(customerDailyWapdaRecords).where(and(eq(customerDailyWapdaRecords.customerId, customer.id), lt(customerDailyWapdaRecords.readingDate, input.readingDate))).orderBy(desc(customerDailyWapdaRecords.readingDate)).limit(1); const previousReading = input.previousReading ?? Number(previousRow?.currentReading ?? 0); const ratePerUnit = input.ratePerUnit ?? Number(customer.unitPrice || DEFAULT_ELECTRICITY_RATE); let calculated: { unitsConsumed: number; totalAmount: number }; try { calculated = calculateManualCustomerReading(previousReading, input.currentReading, ratePerUnit); } catch (error) { throw new TRPCError({ code: "BAD_REQUEST", message: error instanceof Error ? error.message : "Invalid readings." }); } await db.insert(customerDailyWapdaRecords).values({ customerId: customer.id, customerName: customer.name, sNo: customer.sNo, month: input.month, year: input.year, readingDate: input.readingDate, previousReading, currentReading: input.currentReading, unitsConsumed: calculated.unitsConsumed, ratePerUnit, totalAmount: calculated.totalAmount }).onDuplicateKeyUpdate({ set: { customerName: customer.name, sNo: customer.sNo, previousReading, currentReading: input.currentReading, unitsConsumed: calculated.unitsConsumed, ratePerUnit, totalAmount: calculated.totalAmount } }); await syncMonthlyBill(db, customer.id, input.month, input.year); return { success: true, customerId: customer.id, readingDate: input.readingDate, previousReading, ...calculated }; }),
  update: protectedProcedure.input(rowInput).mutation(async ({ ctx, input }) => { await requireAccess(ctx.user, "canManageWapda"); const db = await getDb(); if (!db) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR", message: "Database unavailable" }); const [row] = await db.select().from(customerDailyWapdaRecords).where(eq(customerDailyWapdaRecords.id, input.id)).limit(1); if (!row) throw new TRPCError({ code: "NOT_FOUND", message: "Daily WAPDA record not found." }); if (input.currentReading < input.previousReading) throw new TRPCError({ code: "BAD_REQUEST", message: "Current reading cannot be lower than previous reading." }); const unitsConsumed = getUnits(input.previousReading, input.currentReading); const ratePerUnit = input.ratePerUnit ?? row.ratePerUnit; await db.update(customerDailyWapdaRecords).set({ previousReading: input.previousReading, currentReading: input.currentReading, unitsConsumed, ratePerUnit, totalAmount: Math.round(unitsConsumed * ratePerUnit) }).where(eq(customerDailyWapdaRecords.id, input.id)); await syncMonthlyBill(db, row.customerId, row.month, row.year); return { success: true }; }),
  delete: protectedProcedure.input(z.object({ id: z.number().int().positive() })).mutation(async ({ ctx, input }) => { await requireAccess(ctx.user, "canManageWapda"); const db = await getDb(); if (!db) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR", message: "Database unavailable" }); const [row] = await db.select().from(customerDailyWapdaRecords).where(eq(customerDailyWapdaRecords.id, input.id)).limit(1); if (!row) throw new TRPCError({ code: "NOT_FOUND", message: "Daily WAPDA record not found." }); await db.delete(customerDailyWapdaRecords).where(eq(customerDailyWapdaRecords.id, input.id)); await syncMonthlyBill(db, row.customerId, row.month, row.year); return { success: true }; }),
  summary: protectedProcedure.input(periodInput).query(async ({ ctx, input }) => { await requireAccess(ctx.user, "canViewReports"); const db = await getDb(); if (!db) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR", message: "Database unavailable" }); const rows: any[] = await db.select().from(customerDailyWapdaRecords).where(and(eq(customerDailyWapdaRecords.month, input.month), eq(customerDailyWapdaRecords.year, input.year))).orderBy(asc(customerDailyWapdaRecords.sNo), asc(customerDailyWapdaRecords.readingDate)); const allCustomers: any[] = await db.select().from(customers).orderBy(asc(customers.sNo)); const byCustomer = new Map<number, any>(allCustomers.map(customer => [customer.id, { customerId: customer.id, sNo: customer.sNo, customerName: customer.name, days: 0, units: 0, totalAmount: 0, records: [] }])); for (const row of rows) { const item = byCustomer.get(row.customerId) ?? { customerId: row.customerId, sNo: row.sNo, customerName: row.customerName, days: 0, units: 0, totalAmount: 0, records: [] }; item.days += 1; item.units += row.unitsConsumed; item.totalAmount += row.totalAmount; item.records.push(row); byCustomer.set(row.customerId, item); } return { month: input.month, year: input.year, importedDays: new Set(rows.map(row => row.readingDate)).size, totalRecords: rows.length, totalUnits: rows.reduce((sum, row) => sum + row.unitsConsumed, 0), totalAmount: rows.reduce((sum, row) => sum + row.totalAmount, 0), customers: Array.from(byCustomer.values()).sort((a, b) => a.sNo - b.sNo) }; }),
  summaryRange: protectedProcedure.input(rangeInput).query(async ({ ctx, input }) => { await requireAccess(ctx.user, "canViewReports"); if (input.endDate < input.startDate) throw new TRPCError({ code: "BAD_REQUEST", message: "End date must be on or after start date." }); const db = await getDb(); if (!db) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR", message: "Database unavailable" }); const rows: any[] = await db.select().from(customerDailyWapdaRecords).where(and(eq(customerDailyWapdaRecords.month, input.month), eq(customerDailyWapdaRecords.year, input.year), gte(customerDailyWapdaRecords.readingDate, input.startDate), lte(customerDailyWapdaRecords.readingDate, input.endDate))).orderBy(asc(customerDailyWapdaRecords.sNo), asc(customerDailyWapdaRecords.readingDate)); return { startDate: input.startDate, endDate: input.endDate, ...summarizeCustomerRange(rows) }; }),
});
