import { useEffect, useState } from "react";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Loader2 } from "lucide-react";
import { toast } from "sonner";
import { trpc } from "@/lib/trpc";
import { DEFAULT_ELECTRICITY_RATE } from "@shared/billing";
import { FormField, NumberInput } from "./AppCommon";
import { ImageUpload } from "./ImageUpload";

const blank = { name:"", serialNumber:"", photoUrl:null as string|null, email:"", mobileNumber:"", whatsappNumber:"", cnic:"", address:"", connectionDate:"", installationDate:"", unitPrice:String(DEFAULT_ELECTRICITY_RATE), meterNumber:"", meterType:"", meterLocation:"", latestMeterPhotoUrl:null as string|null };

export function CustomerDialog({ open, onOpenChange, customer }: { open: boolean; onOpenChange: (open:boolean) => void; customer?: any }) {
  const [form, setForm] = useState(blank);
  const utils = trpc.useUtils();
  const save = trpc.customers.save.useMutation({ onSuccess: () => { toast.success(customer ? "Customer updated" : "Customer created"); utils.customers.invalidate(); onOpenChange(false); }, onError: e => toast.error(e.message) });
  useEffect(() => { if (open) setForm(customer ? { ...blank, ...customer, serialNumber:String(customer.sNo ?? customer.serialNumber), unitPrice:String(customer.unitPrice) } : blank); }, [open, customer]);
  const set = (key:string, value:any) => setForm(f => ({...f,[key]:value}));
  const submit = (e: React.FormEvent) => { e.preventDefault(); if (!form.name.trim()) return toast.error("Customer name is required"); const requestedSNo = form.serialNumber.trim() ? Number(form.serialNumber) : undefined; if (form.serialNumber.trim() && !requestedSNo) return toast.error("Enter a valid sNo"); save.mutate({ id: customer?.id, name:form.name.trim(), sNo:requestedSNo, serialNumber:requestedSNo, photoUrl:form.photoUrl, email:form.email || null, mobileNumber:form.mobileNumber || null, whatsappNumber:form.whatsappNumber || null, cnic:form.cnic || null, address:form.address || null, connectionDate:form.connectionDate || null, installationDate:form.installationDate || null, unitPrice:Number(form.unitPrice) || DEFAULT_ELECTRICITY_RATE, meterNumber:form.meterNumber || null, meterType:form.meterType || null, meterLocation:form.meterLocation || null, latestMeterPhotoUrl:form.latestMeterPhotoUrl }); };
  return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="max-h-[92vh] max-w-4xl overflow-y-auto"><form onSubmit={submit}><DialogHeader><DialogTitle className="text-2xl">{customer ? "Edit customer" : "Add new customer"}</DialogTitle><DialogDescription>Customer, connection, pricing, and meter information.</DialogDescription></DialogHeader><div className="mt-5 grid gap-5 lg:grid-cols-[1fr_260px]"><div className="form-grid"><FormField label="Customer name" required><Input value={form.name} onChange={e=>set("name",e.target.value)} /></FormField><FormField label="sNo (blank = first vacant number)" required><NumberInput step="1" value={form.serialNumber} onChange={e=>set("serialNumber",e.target.value)} /></FormField><FormField label="Mobile"><Input value={form.mobileNumber} onChange={e=>set("mobileNumber",e.target.value)} /></FormField><FormField label="WhatsApp"><Input value={form.whatsappNumber} onChange={e=>set("whatsappNumber",e.target.value)} /></FormField><FormField label="Email"><Input type="email" value={form.email} onChange={e=>set("email",e.target.value)} /></FormField><FormField label="CNIC"><Input value={form.cnic} onChange={e=>set("cnic",e.target.value)} /></FormField><FormField label="Connection date"><Input type="date" value={form.connectionDate} onChange={e=>set("connectionDate",e.target.value)} /></FormField><FormField label="Installation date"><Input type="date" value={form.installationDate} onChange={e=>set("installationDate",e.target.value)} /></FormField><FormField label="Unit price"><NumberInput value={form.unitPrice} onChange={e=>set("unitPrice",e.target.value)} /></FormField><FormField label="Meter number"><Input value={form.meterNumber} onChange={e=>set("meterNumber",e.target.value)} /></FormField><FormField label="Meter type"><Input value={form.meterType} onChange={e=>set("meterType",e.target.value)} /></FormField><FormField label="Meter location / area"><Input value={form.meterLocation} onChange={e=>set("meterLocation",e.target.value)} /></FormField><FormField label="Address" className="sm:col-span-2"><Textarea rows={3} value={form.address} onChange={e=>set("address",e.target.value)} /></FormField></div><div className="grid content-start gap-4"><ImageUpload label="Customer photo" category="customer" value={form.photoUrl} onChange={v=>set("photoUrl",v)}/><ImageUpload label="Latest meter photo" category="meter" value={form.latestMeterPhotoUrl} onChange={v=>set("latestMeterPhotoUrl",v)}/></div></div><DialogFooter className="mt-6"><Button type="button" variant="outline" onClick={()=>onOpenChange(false)}>Cancel</Button><Button type="submit" disabled={save.isPending}>{save.isPending && <Loader2 className="mr-2 h-4 w-4 animate-spin"/>}{customer ? "Save changes" : "Create customer"}</Button></DialogFooter></form></DialogContent></Dialog>;
}
