import { useEffect, useMemo, useState } from "react";
import { useLocation } from "wouter";
import { trpc } from "@/lib/trpc";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { EmptyState, LoadingState, PageHeader, PeriodSelector, StatusBadge } from "@/components/AppCommon";
import { CustomerDialog } from "@/components/CustomerDialog";
import { BillDialog } from "@/components/BillDialog";
import { BulkImportDialog } from "@/components/BulkImportDialog";
import { downloadCsv } from "@/lib/export";
import { formatRs, MONTHS } from "@shared/billing";
import { Area, AreaChart, Bar, BarChart, CartesianGrid, Cell, Line, LineChart, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { Banknote, Building2, CircleDollarSign, Clock3, Download, FileBarChart, FileJson, History, Plus, ReceiptText, Search, TrendingUp, Users, WalletCards, Zap } from "lucide-react";
import { toast } from "sonner";

const metrics=[
  ["customers","Total Customers",Users],["bills","Total Bills",ReceiptText],["units","Total Units",Zap],["billed","Total Bill Amount",Banknote],["received","Total Received",CircleDollarSign],["outstanding","Outstanding",Clock3],["profit","Net Profit",TrendingUp],["paid","Paid Customers",Users],["unpaid","Unpaid Customers",Users],["previousOutstanding","Previous Balance",WalletCards],
] as const;
export default function Home(){
  const [,navigate]=useLocation(); const now=new Date(); const [month,setMonth]=useState(now.getMonth()+1),[year,setYear]=useState(now.getFullYear()); const [periodSet,setPeriodSet]=useState(false); const [search,setSearch]=useState(""); const [customerOpen,setCustomerOpen]=useState(false),[billOpen,setBillOpen]=useState(false),[editingBill,setEditingBill]=useState<any>(); const [bulkImportOpen,setBulkImportOpen]=useState(false); const utils=trpc.useUtils();
  const latest=trpc.overview.latestPeriod.useQuery(); const access=trpc.admin.myAccess.useQuery();
  useEffect(()=>{if(!periodSet&&latest.data){setMonth(latest.data.month);setYear(latest.data.year);setPeriodSet(true)}},[latest.data,periodSet]);
  const dashboard=trpc.overview.dashboard.useQuery({month,year}); const data=dashboard.data; const totals:any=data?.totals||{};
  const filtered=useMemo(()=>data?.bills.filter((b:any)=>!search||b.customerName.toLowerCase().includes(search.toLowerCase())||b.invoiceNumber.toLowerCase().includes(search.toLowerCase()))||[],[data,search]);
  const quick: Array<[string, any, () => void, boolean | undefined, boolean?]> = [
    ["New Customer",Users,()=>setCustomerOpen(true),access.data?.canManageCustomers],["New Bill",Plus,()=>{setEditingBill(undefined);setBillOpen(true)},access.data?.canManageBills],["Ledger",WalletCards,()=>navigate("/ledger"),true],["Report PDF",FileBarChart,()=>navigate("/report"),true],["History",History,()=>navigate("/history"),true],["All Bills PDF",ReceiptText,()=>navigate("/bills"),true],["CSV Export",Download,()=>filtered.length?downloadCsv(`bills-${year}-${month}.csv`,filtered.map((b:any)=>({Invoice:b.invoiceNumber,Customer:b.customerName,Month:MONTHS[b.month-1],Year:b.year,Units:b.unitsConsumed,Total:b.totalPayable,Received:b.receivedAmount,Outstanding:b.outstandingAmount,Status:b.status}))):toast.info("No bills are available to export for this period."),true],["Bulk Import (JSON)",FileJson,()=>setBulkImportOpen(true),access.data?.canManageCompany],["Company Settings",Building2,()=>navigate("/company-settings"),access.data?.canManageCompany],
  ];
  const categoryStyles: Record<string, { badge: string; edge: string; description: string }> = {
    "New Customer": { badge: "bg-[#1479d1]", edge: "border-l-[#1479d1]", description: "Add and manage new customers." },
    "New Bill": { badge: "bg-[#079b67]", edge: "border-l-[#079b67]", description: "Generate and manage customer bills." },
    Ledger: { badge: "bg-[#159eb4]", edge: "border-l-[#159eb4]", description: "View customer ledger and transaction details." },
    "Report PDF": { badge: "bg-[#e5484d]", edge: "border-l-[#e5484d]", description: "Generate and download reports in PDF format." },
    History: { badge: "bg-[#f29a05]", edge: "border-l-[#f29a05]", description: "Check past records and transaction history." },
    "All Bills PDF": { badge: "bg-[#633bb7]", edge: "border-l-[#633bb7]", description: "Download all bills in PDF format." },
    "CSV Export": { badge: "bg-[#1479d1]", edge: "border-l-[#1479d1]", description: "Export data in CSV format for analysis." },
    "Bulk Import (JSON)": { badge: "bg-[#4f46e5]", edge: "border-l-[#4f46e5]", description: "Import data using JSON file." },
    "Company Settings": { badge: "bg-[#334155]", edge: "border-l-[#334155]", description: "Manage business identity and payment details." },
  };
  if(dashboard.isLoading)return <LoadingState label="Preparing dashboard…"/>;
  if(dashboard.error)return <EmptyState title="Dashboard unavailable" description={dashboard.error.message}/>;
  const trend=data?.trend.map((r:any)=>({...r,name:MONTHS[r.month-1].slice(0,3)}))||[];
  return <><section className="dashboard-hero mb-6 overflow-hidden rounded-[28px] border border-[#a7d9f1] px-5 py-6 shadow-[0_16px_40px_rgba(20,107,176,0.12)] sm:px-8 sm:py-8"><div className="relative z-10 max-w-2xl"><div className="mb-5 inline-flex items-center gap-3 rounded-full bg-[#063b91] px-4 py-2 text-xs font-bold uppercase tracking-[.14em] text-white shadow-lg"><TrendingUp className="h-4 w-4"/> Executive overview</div><h1 className="display-font text-4xl font-normal leading-tight text-[#063b6f] sm:text-6xl">Business <span className="text-[#e9a900]">Dashboard</span></h1><p className="mt-3 max-w-xl text-base leading-7 text-[#31577c] sm:text-lg">Collection, outstanding, WAPDA expense, and profit for {MONTHS[month-1]} {year}.</p><div className="mt-6 flex flex-wrap gap-3"><PeriodSelector month={month} year={year} onMonth={setMonth} onYear={setYear}/></div></div><div className="dashboard-hero-sun"/><div className="dashboard-hero-panel"/></section>
  <div className="action-card-grid mb-7 grid grid-cols-1 gap-4 sm:grid-cols-2">{quick.filter(q=>q[3]).map(([label,Icon,action,,disabled])=>{const style=categoryStyles[String(label)]||categoryStyles["Company Settings"];return <Button key={String(label)} variant="outline" onClick={action as any} disabled={disabled} className={`action-card group h-auto min-h-[154px] items-center justify-start gap-4 rounded-[22px] border border-[#d8e2ef] border-l-[7px] bg-white px-5 py-5 text-left text-[#0a236b] shadow-[0_7px_20px_rgba(15,23,42,0.08)] hover:-translate-y-1 hover:scale-[1.01] hover:border-[#c1d7ed] hover:bg-white hover:text-[#0a236b] hover:shadow-[0_14px_30px_rgba(15,23,42,0.14)] ${style.edge}`}><span className={`action-icon-badge flex h-[70px] w-[70px] shrink-0 items-center justify-center rounded-[20px] text-white shadow-md ${style.badge}`}><Icon className="h-9 w-9"/></span><span className="min-w-0 flex-1"><span className="block text-xl font-extrabold leading-tight">{label}</span><span className="mt-2 block line-clamp-2 max-w-[260px] text-sm font-medium leading-6 text-[#49637f]">{style.description}</span></span><span className="action-arrow z-10 flex h-11 w-11 shrink-0 items-center justify-center rounded-full bg-[#edf6ff] text-2xl text-[#1678c7] transition-transform group-hover:translate-x-1">›</span></Button>})}</div>
  <div className="mb-6 grid grid-cols-2 gap-3 lg:grid-cols-5">{metrics.map(([key,label,Icon])=>{const value=totals[key]??0;const money=["billed","received","outstanding","profit","previousOutstanding"].includes(key);return <Card key={key} className="metric-card glass-card"><CardContent className="p-4"><div className="mb-3 flex h-9 w-9 items-center justify-center rounded-xl bg-[#1a2b4a] text-[#d9ad51]"><Icon className="h-4 w-4"/></div><p className="text-xs font-semibold text-muted-foreground">{label}</p><p className={`mt-1 text-lg font-extrabold sm:text-xl ${key==="profit"&&value<0?"text-destructive":""}`}>{money?formatRs(value):Number(value).toLocaleString()}</p>{key==="profit"&&<p className="mt-1 text-[10px] text-muted-foreground">after {formatRs(totals.wapdaExpense)} WAPDA</p>}</CardContent></Card>})}</div>
  <div className="mb-6 grid gap-4 xl:grid-cols-2"><ChartCard title="Monthly Collection"><ResponsiveContainer width="100%" height={260}><BarChart data={trend}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="name"/><YAxis width={50}/><Tooltip formatter={(v:any)=>formatRs(v)}/><Bar dataKey="received" fill="#c8932e" radius={[6,6,0,0]}/></BarChart></ResponsiveContainer></ChartCard><ChartCard title="Paid vs Unpaid"><ResponsiveContainer width="100%" height={260}><PieChart><Pie data={[{name:"Paid",value:totals.paid||0},{name:"Unpaid",value:totals.unpaid||0}]} dataKey="value" innerRadius={55} outerRadius={88} paddingAngle={4}>{["#34745b","#c8932e"].map(c=><Cell key={c} fill={c}/>)}</Pie><Tooltip/></PieChart></ResponsiveContainer></ChartCard><ChartCard title="Units Consumption"><ResponsiveContainer width="100%" height={260}><AreaChart data={trend}><defs><linearGradient id="units" x1="0" y1="0" x2="0" y2="1"><stop offset="5%" stopColor="#1a2b4a" stopOpacity={.45}/><stop offset="95%" stopColor="#1a2b4a" stopOpacity={.02}/></linearGradient></defs><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="name"/><YAxis width={50}/><Tooltip/><Area type="monotone" dataKey="units" stroke="#1a2b4a" fill="url(#units)" strokeWidth={3}/></AreaChart></ResponsiveContainer></ChartCard><ChartCard title="Profit Trend"><ResponsiveContainer width="100%" height={260}><LineChart data={trend}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="name"/><YAxis width={50}/><Tooltip formatter={(v:any)=>formatRs(v)}/><Line type="monotone" dataKey="profit" stroke="#34745b" strokeWidth={3} dot={{fill:"#c8932e"}}/></LineChart></ResponsiveContainer></ChartCard></div>
  <Card className="glass-card"><CardHeader><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><CardTitle>Monthly bills</CardTitle><div className="relative w-full sm:w-80"><Search className="absolute left-3 top-3 h-4 w-4 text-muted-foreground"/><Input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search name or invoice…" className="pl-9"/></div></div></CardHeader><CardContent>{!filtered.length?<EmptyState title="No bills found" description="Create the first bill for this month to begin tracking collections." actionLabel={access.data?.canManageBills?"Create Bill":undefined} onAction={()=>setBillOpen(true)}/>:<div className="grid gap-5 lg:grid-cols-2"><BillSection title="Unpaid / Overdue" bills={filtered.filter((b:any)=>b.status!=="Paid")} onView={(id:number)=>navigate(`/print/${id}`)} onEdit={access.data?.canManageBills?(b:any)=>{setEditingBill(b);setBillOpen(true)}:undefined}/><BillSection title="Paid" bills={filtered.filter((b:any)=>b.status==="Paid")} onView={(id:number)=>navigate(`/print/${id}`)} onEdit={access.data?.canManageBills?(b:any)=>{setEditingBill(b);setBillOpen(true)}:undefined}/></div>}</CardContent></Card>
  <BulkImportDialog open={bulkImportOpen} onOpenChange={setBulkImportOpen} onImported={async()=>{await Promise.all([utils.customers.invalidate(),utils.bills.invalidate(),utils.overview.invalidate()]);}}/><CustomerDialog open={customerOpen} onOpenChange={setCustomerOpen}/><BillDialog open={billOpen} onOpenChange={setBillOpen} bill={editingBill} initialMonth={month} initialYear={year}/></>;
}
function ChartCard({title,children}:{title:string;children:any}){return <Card className="glass-card"><CardHeader><CardTitle className="text-lg">{title}</CardTitle></CardHeader><CardContent className="px-2 sm:px-6">{children}</CardContent></Card>}
  function BillSection({title,bills,onView,onEdit}:{title:string;bills:any[];onView:(id:number)=>void;onEdit?:((b:any)=>void)}){return <div><h3 className="mb-3 text-sm font-extrabold uppercase tracking-[.15em] text-muted-foreground">{title} ({bills.length})</h3><div className="space-y-2">{bills.length?bills.map(b=><div key={b.id} className="flex min-h-16 items-center justify-between gap-3 rounded-xl border bg-card p-3"><div className="min-w-0"><p className="truncate text-sm font-bold">#{b.customerSNo ?? "—"} - {b.customerName}</p><p className="text-xs text-muted-foreground">{b.invoiceNumber} · {formatRs(b.totalPayable)}</p></div><div className="flex shrink-0 items-center gap-2"><StatusBadge status={b.status}/><Button size="sm" variant="outline" className="min-h-10" onClick={()=>onView(b.id)}>View</Button>{onEdit&&<Button size="sm" className="min-h-10" onClick={()=>onEdit(b)}>Edit</Button>}</div></div>):<p className="rounded-xl border border-dashed p-5 text-center text-sm text-muted-foreground">No {title.toLowerCase()} bills.</p>}</div></div>}
